runtime: python39
entrypoint: streamlit run src/dashboard/app.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS false --browser.gatherUsageStats false

instance_class: F1  # Free tier instance

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5  # Adjust based on usage

env_variables:
  PYTHONUNBUFFERED: "true"
